services:

  # Postgres db
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: >
        pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
        && psql -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c "SELECT 1"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  # Setup the database
  flyway:
    image: flyway/flyway:10-alpine
    volumes:
      - ./flyway/sql:/flyway/db/migrations
    environment:
      FLYWAY_URL: ${POSTGRES_URL}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      FLYWAY_LOCATIONS: filesystem:/flyway/db/migrations
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    command: migrate
    depends_on:
      postgres:
        condition: service_healthy

  # The Restate platform server
  restate-server:
    image: docker.restate.dev/restatedev/restate:1.3
    restart: always
    ports:
      - "8080:8080"
      - "9070:9070"
      - "9071:9071"

  # This is the customer facing rest endpoint in Ktor
  rest-server:
    image: ivan/rest-server
    restart: always
    ports:
      - "9000:9000"
    environment:
      SERVICE_TRANSACTION_RESTATE_URL: ${SERVICE_TRANSACTION_RESTATE_URL}
      SERVICE_PAYMENT_RESTATE_URL_TEMPLATE: ${SERVICE_PAYMENT_RESTATE_URL_TEMPLATE}
    depends_on:
      - transaction-service
      - stats-service

  # this is the service for account module
  payment-service:
    image: ivan/payment-service
    restart: always
    ports:
      - "9080:9080"
    environment:
      PORT: 9080

  # this is the service for account module
  account-service:
    image: ivan/account-service
    restart: always
    ports:
      - "9081:9080"
    environment:
      PORT: 9080

  # This is the service for transaction module
  transaction-service:
    image: ivan/transaction-service
    restart: always
    ports:
      - "9082:9080"
    environment:
      PORT: 9080
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  # this is the service for stats module
  stats-service:
    image: ivan/stats-service
    restart: always
    ports:
      - "9083:9080"
    environment:
      PORT: 9080

volumes:
  db-data: